// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx4AZFMblepzGwdt1VVFUtht4iw36J7Tw',
    appId: '1:66915416626:web:00d5ecb6d125b6c8401a2b',
    messagingSenderId: '66915416626',
    projectId: 'my-notes-new-flutter-app-06',
    authDomain: 'my-notes-new-flutter-app-06.firebaseapp.com',
    storageBucket: 'my-notes-new-flutter-app-06.appspot.com',
    measurementId: 'G-QCCGSKHSWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkPHh-PBeCuwh2SyQqLcptJw8mY2FuDw',
    appId: '1:66915416626:android:1fe3611601a5cae0401a2b',
    messagingSenderId: '66915416626',
    projectId: 'my-notes-new-flutter-app-06',
    storageBucket: 'my-notes-new-flutter-app-06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcjKcfaORow8umDJgl5Zp2VsRGot7uIBk',
    appId: '1:66915416626:ios:6ff2de4b2b817049401a2b',
    messagingSenderId: '66915416626',
    projectId: 'my-notes-new-flutter-app-06',
    storageBucket: 'my-notes-new-flutter-app-06.appspot.com',
    iosBundleId: 'com.Spaceexplorer06.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcjKcfaORow8umDJgl5Zp2VsRGot7uIBk',
    appId: '1:66915416626:ios:03372a21deaecde5401a2b',
    messagingSenderId: '66915416626',
    projectId: 'my-notes-new-flutter-app-06',
    storageBucket: 'my-notes-new-flutter-app-06.appspot.com',
    iosBundleId: 'com.Spaceexplorer06.mynotes.RunnerTests',
  );
}
